name: RejuvenationSacks
version: '0.0.1'
main: com.alicedev.rejuvenationSacks.RejuvenationSacks
api-version: '1.21'
commands:
  prsacks:
    description: RejuvenationSacks main command.
    usage: /prsacks <reload>
    permission: rejuvenationsacks.reload
  gensack:
    description: Generates a new Sack and sends it to the target player (or self if none).
    usage: /gensack <template_id> [target_player]
    permission: rejuvenationsacks.generate
